### PR TITLE
Snapshot tracker improvement and new tracker added

### PR DESCRIPTION
**Pull request by quevon24**
This PR split Snapshot class in multiple methods so you can create your custom tracker more easily inheriting from Snapshot class.

The PR also contains a new tracker derived from the Snapshot class to snapshot OLD on Update and Delete, this tracker also allows the user to exclude field names and auto_now fields in the generated sql to compare the rows as mentioned in #83 and #78

Let me know what you think about these new features, feedback always welcome

### CODE REVIEW

**Review by mlissner — COMMENTED** [review]
@wesleykendall will be the boss, but this looks great to me. I think I'd suggest we remove the stuff related to ignore_auto_now_fields from this PR and do it as a separate one after this is merged, but this clearly lays the groundwork for it. If we do it as a separate PR, I'd suggest that it be added as a feature to `Snapshot` so that all other classes can take advantage of it.

**Comment by mlissner** [comment]
@quevon24 can you say what's going on with the tests?

**Comment by quevon24** [comment]
@mlissner I've been following the guidelines for contributing, but I was having trouble with a few things

When i try to run the full test suite i get a lots of errors, for some reason tox keeps reusing the database and throwing errors like "django.db.utils.ProgrammingError: relation "tests_afterupdateordeletesnapshotmodel" already exists" or "psycopg2.errors.DuplicateTable: relation "tests_afterupdateordeletesnapshotmodel" already exists" (circleci tests are correct, but causing problems locally) Because of this i can't run my tests locally and then commit them to this PR

Also, the hot reload doesn't seems to work correctly. I did some tests to generate the required migrations, i removed some migration files, and the coverage report throws errors like "No source for code: '/code/pghistory/tests/migrations/0005_auto_20230321_2306.py'" because files are not being reloaded.

I'm trying to figure out the things i mentioned above to finish writing some tests for the new Snapshot class

**Comment by quevon24** [comment]
> When i try to run the full test suite i get a lots of errors, for some reason tox keeps reusing the database and throwing errors like "django.db.utils.ProgrammingError: relation "tests_afterupdateordeletesnapshotmodel" already exists" or "psycopg2.errors.DuplicateTable: relation "tests_afterupdateordeletesnapshotmodel" already exists" (circleci tests are correct, but causing problems locally) Because of this i can't run my tests locally and then commit them to this PR

For the error with the db i realized that there is a host volume pointing to /var/lib/postgresql/data, i just deleted the host volume and regenerated it again, and the errors are gone


> Also, the hot reload doesn't seems to work correctly. I did some tests to generate the required migrations, i removed some migration files, and the coverage report throws errors like "No source for code: '/code/pghistory/tests/migrations/0005_auto_20230321_2306.py'" because files are not being reloaded.

The problem wasn't with the hot reload, to solve this i deleted the .coverage file that is generated when you run tox

By the way, the library seems to not support WSL, it gets stuck trying to resolve dependencies.

**Comment by quevon24** [comment]
I added tests for possible params variations for the custom snapshot class

**Comment by mlissner** [comment]
Can you remove the stuff that does custom field ignoring so we can add it in a future PR instead?

**Comment by quevon24** [comment]
@mlissner changes are ready

**Comment by mlissner** [comment]
LGTM!

**Comment by wesleykendall** [comment]
@quevon24 @mlissner , I commented on https://github.com/Opus10/django-pghistory/issues/83 since it's relevant to this comment.

I believe the additions to the `Snapshot` class here were motivated by #83, right? If my understanding is correct, your issue can already be solved without modifying Snapshot. I.e. by supplying a `Condition` object to the `condition` argument. If this is the case, I would prefer to keep the `Snapshot` class the same and keep these classes simple

For this tracker, it's going to diverge from the other utility trackers like `AfterInsertOrUpdate`. The other utility trackers are meant to be barebones - no automatic conditions, etc. If this change goes in the library ideally it would behave like every other barebones utility tracker:

```
class BeforeUpdateOrDelete(PreconfiguredDatabaseTracker):
    """
    A database tracker that snapshots the old row during an update or delete
    """

    operation = pgtrigger.Update | pgtrigger.Delete
    snapshot = "OLD"
```

(note I named it "Before..." instead of "After...". django-pghistory has a somewhat confusing way of naming these trackers. They're named after the row they're snapshotting, not when the trigger fires).

Once this barebones tracker is in, you also want to put conditions on it so it behaves more like the default `Snapshot` tracker, right? I.e. ignore snapshotting when fields don't change or when excluded fields don't change).

If that's the case, I'd say let's get this barebones tracker in and I can follow up with a PR that makes it easier to add these conditions. Perhaps in the next major version release I can refactor how all of these utility classes work and just have everything be based off of `Snapshot`

**Comment by wesleykendall** [comment]
Let's discuss a bit more and I'll try to get in the changes next release

**Comment by mlissner** [comment]
Thanks for the detailed and thoughtful reply, Wes. 

> Once this barebones tracker is in, you also want to put conditions on it so it behaves more like the default Snapshot tracker, right? I.e. ignore snapshotting when fields don't change or when excluded fields don't change).

Yes, exactly. 

> If that's the case, I'd say let's get this barebones tracker in

We'll revise this PR to simplify it down to the barebones tracker, sure.

>  and I can follow up with a PR that makes it easier to add these conditions

That'd be fantastic, thank you! I think that'd nail all of our needs, yes!

**Comment by quevon24** [comment]
@mlissner @wesleykendall I removed everything from the custom snapshot, i only left the before update or delete backbone trigger

I was thinking of a possible way to let the user have more control for the conditions, maybe one option would be to have some preconfigured conditions that could be used in any of the barebone trackers or also allow the user to create their custom preconfigured conditions using a class that can do the same as Snapshot class when it generates the condition to compare OLD and NEW rows.

Something like:

`@pghistory.track(BeforeUpdateOrDelete(condition=pghistory.compare_rows), exclude=["date_modified"])`

pghistory.compare_rows will be a preconfigured condition(maybe a class that can be reused and have access to event model) and will have the job to generate the pgtrigger Condition using the model fields(the ones tracked)

And from there the user will have the possibility to build their custom conditions without having to repeat the condition on every pghistory decorator (currentry if you need something complex in the condition, you need to manually write each condition to pass it to the barebone tracker)

**Comment by wesleykendall** [comment]
Hey @quevon24 @mlissner 

I have a change ready to add to this PR in addition to what you have. I wanted to first run it by you first. The change is more in-line with your original PR and makes some edits to the base class to make it less cumbersome.

Preface - I thought about your suggestion a lot, and it's going to be difficult to support that style at the moment because of how things are designed. The `condition` parameter is just being passed directly to a trigger from `django-pgtrigger`, and this object has no idea what the model even is until the time the trigger is installed. There would have to be some trickery somewhere to support what you suggested, and it might be easier to support something like this in a totally different interface in the next major version release.

I completely agree that there should be an easier way for people to make custom trackers for their models though, along with not needing to repeat yourself everywhere in a decorator. Here's what I came up with for now. Let me know what you think.

## Approach

I made some changes that were more in-line with your original PR that edited the base class:

1. I added a utility to the base `DatabaseTracker` object to more easily add/create the snapshot triggers.
2. I made a standalone `Changed` condition object. This allows you to easily create a condition that will fire when configured fields change. By default, it fires when any field changes.

With these changes, the `Snapshot` `setup` method now looks like this:

```
def setup(self, event_model):
    self.add_event_trigger(
        event_model=event_model,
        label=self.label,
        name=f"{self.label}_insert",
        snapshot="NEW",
        when=pgtrigger.After,
        operation=pgtrigger.Insert,
    )

    self.add_event_trigger(
        event_model=event_model,
        label=self.label,
        name=f"{self.label}_update",
        snapshot="NEW",
        when=pgtrigger.After,
        operation=pgtrigger.Update,
        condition=Changed(event_model),
    )
```

I.e. the Insert trigger doesn't have a condition, and the Update trigger uses the `Changed` utility condition. It fires on any changed field by default.

With this in mind, I believe it should be easier for you to make your own base class to do what you want. Here's an example of a tracker that snapshots OLD rows on update/delete:

```
class CustomSnapshot(pghistory.Snapshot):
    def setup(self, event_model):
        self.add_event_trigger(
            event_model=event_model,
            label=self.label,
            name=f"{self.label}_update",
            snapshot="OLD",
            when=pgtrigger.After,
            operation=pgtrigger.Update,
            condition=Changed(event_model),
        )

        self.add_event_trigger(
            event_model=event_model,
            label=self.label,
            name=f"{self.label}_delete",
            snapshot="OLD",
            when=pgtrigger.After,
            operation=pgtrigger.Delete,
        )
```

Let's take this a bit further and only save snapshots when important fields change (i.e. no auto fields).

```
class IgnoreAutoFieldsSnapshot(pghistory.Snapshot):
    def setup(self, event_model):
        # Warning - this is pseudocode
        fields_to_watch = [f.name for f in event_model.pgh_tracked_model._meta.fields if not is_auto_field(f)]

        self.add_event_trigger(
            event_model=event_model,
            label=self.label,
            name=f"{self.label}_update",
            snapshot="OLD",
            when=pgtrigger.After,
            operation=pgtrigger.Update,
            # The condition here ensures we only make a snapshot when an important field changes
            condition=Changed(event_model, fields=fields_to_watch),
        )

        self.add_event_trigger(
            event_model=event_model,
            label=self.label,
            name=f"{self.label}_delete",
            snapshot="OLD",
            when=pgtrigger.After,
            operation=pgtrigger.Delete,
        )
```

With this, you now set up your trackers like:

```
@pghistory.track(IgnoreAutoFieldsSnapshot())
class MyModel(models.Model):
   ...
```

I.e., you'll be snapshotting all fields, but you'll only be storing updates when the important fields change. Again, not the prettiest interface ever, but it should be much better than before.

## Follow up

Does this support your use case? I already have the code ready and can add it in this PR alongside the other utility you added.

If it does, I'll quickly add a test case for a custom tracker like this to double check my logic here. I'll follow up in another PR with an example in the docs. Perhaps we can think of another way to address this in the next major version release. The current interface makes it somewhat cumbersome

**Comment by mlissner** [comment]
This looks great to me. It doesn't even seem all that cumbersome. Sure, it'd be nice to do something like:

```
class CustomSnapshotter(UpdateSnaptshotter, DeleteSnapshotter):
    ignored_fields = ["date_modified"]
```

That'd be nice, sure, a dream even, but your solution above is absolutely fine and we'd be perfectly happy with it — unless @quevon24 sees something I don't?

**Comment by quevon24** [comment]
@wesleykendall Your solution looks great, i think it suits our needs, it also greatly reduced code required to add the event triggers and maybe we could use _Changed_ class or method as a guide in case we need to generate a different condition.

I'm looking forward to seeing those changes in the PR, thanks for the effort you make for this library.

**Comment by wesleykendall** [comment]
thanks for letting me know!

The release notes are generated from the commit log, so I'm going to squash your commit and then add one more commit with those changes. The change will be part of 2.7.0. Will let you know when it's deployed

**Comment by wesleykendall** [comment]
@quevon24 I added the change! I updated the test suite to include that custom tracker as an example. I added you as the commit author for both commits since this change was so similar to your initial PR. Will let you know when it's released

**Comment by wesleykendall** [comment]
released in v2.7

**Comment by mlissner** [comment]
Woo hoo! Thanks Wes! We'll take a look ASAP.

**Pull request merged**
