### PR TITLE
Fix 6 multi table inheritance

### PR DESCRIPTION
**Pull request by pierreben**
Hi,

In response to this ticket: https://github.com/Opus10/django-pghistory/issues/6:

I've created a fix to improve AggregateEvent query to also retrieve the parents values and their related models in case of multiple and complex inheritance.

I've added a test to validate the changes, and I've run the formater and the linter.

Can you give me your feedback on these updates ?

Many thanks !

### CODE REVIEW

**Comment by wesleykendall** [comment]
@pierreben thanks for the change. I'm having a hard time figuring out what is different though because there are very many style changes. Even all single quotes are changed to double quotes.

I think you might have ran black with a different configuration.

I'll see if I can revert some of these changes myself

**Comment by wesleykendall** [comment]
@pierreben I removed the commit that did black formatting, and that seemed to clear up the diff quite a bit.

I'm not totally sure I follow how this works with aggregate event tracking, but give me some more time to play around with it and understand.

If I understand correctly, this is merging together the parents with the children in the aggregate events? I wasn't sure what was going on in that code

**Comment by pierreben** [comment]
Hi @wesleykendall ,

Thank you for all the time you spent on reformatting the code, sorry that my editor applies black everywhere.

This is quite a complex subject, so I think the best to help is that I put comments on the changes directly to illustrate them.

Don't hesitate to tell me if after these comments you need more details !

**Comment by pierreben** [comment]
@wesleykendall , I've tried to explain my updates as best as I could (sorry for my poor english).
I hope that it can help to understand how it works, don't hesitate to tell me if you need more details or explanations !

**Comment by pierreben** [comment]
Hello @wesleykendall , I allow myself to follow up about this issue. 
Don't hesitate to ask me for more details :)

**Comment by wesleykendall** [comment]
Apologies for letting this PR get too stale. There have been many changes to pghistory since this and the original issue opened at https://github.com/Opus10/django-pghistory/issues/6

Although I don't think we have "full support" for concrete inheritance, there are ways to work around it for now mentioned at the end of that issue.

If people have other thoughts on how to better support concrete inheritance, please [open a discussion](https://github.com/Opus10/django-pghistory/discussions/new/choose) and perhaps we can revisit this original PR if it still might solve inadequacies in the current version of pghistory

**Pull request closed without merging**
