### PR TITLE
Add JSONEncoder extension to handle types like uuid in metadata

### PR DESCRIPTION
**Pull request by jzmiller1**
Type: trivial

### CODE REVIEW

**Comment by jzmiller1** [comment]
Looking to address issue #32 .  Don't want to get too far without some feedback on this being a good idea or not.  If you would like for me to do some additional work on tests I can do that as well.

**Comment by jzmiller1** [comment]
Now that I think about it some more it probably makes more sense to make this a pluggable thing via settings so the that pghistory project is not trying to update it for whatever objects people want to put in the metadata.  Will hopefully be able to update this with that approach soon.

**Comment by wesleykendall** [comment]
@jzmiller1 thanks for opening!
 
Quick note - I'm finally going to be doing a big overhaul on pghistory next week and blasting through all of the issues like I did with pgtrigger the past weeks. It's in need of some love!

Thanks for adding this. Here are my thoughts, and I'm happy to take this past the finish line tonight if you're fine with these changes:

1. I like the setting you made. I would recommend calling it `PGHISTORY_JSON_ENCODER`
2. Have the setting default to `"django.core.serializers.json.DjangoJSONEncoder"` (see [the code](https://github.com/django/django/blob/main/django/core/serializers/json.py#L77)), which handles datetimes, decimals, uuids, promises, and times.

I'm a little skeptical about putting IP addresses and things outside of the default Django encoder in it and like to just let users override this stuff for their use cases.

If you're good with this, I can make the changes, add the docs, and also label this a "feature" that will appear in the release notes

**Comment by jzmiller1** [comment]
Of course!  All that sounds great to me.

**Comment by wesleykendall** [comment]
@jzmiller1 thanks again for the help! The changes have been made and will be released soon. There's now a configurable setting called `PGHISTORY_JSON_ENCODER` that defaults to Django's.

I punted on updating the docs for now because I'm going to do a pretty significant overhaul on the docs next week. Will be combing through a lot of the issues too

**Comment by wesleykendall** [comment]
Released in version 2.1

**Comment by jzmiller1** [comment]
Awesome!  I'll upgrade to the new version and give it a shot.  Thanks for your work!

**Pull request merged**
