### PR TITLE
Add user IP address to middleware context

### PR DESCRIPTION
**Pull request by wgordon17**
Type: feature

### CODE REVIEW

**Comment by wgordon17** [comment]
@wesleykendall Not sure what the wide opinions are on something like this, but it would definitely help for my tracking use cases

**Comment by wesleykendall** [comment]
@wgordon17 I think this is best left as a subclass inside of a project instead of in the middleware that everyone uses. I'm happy to accept a PR that adds an example to the docs on how to extend the middleware. Just cautious about bringing in another dependency and adding more data to the tracked history

**Comment by jacklinke** [comment]
Agreed. Subclassing (or just copying and editing) a project-specific middleware class is the best approach for folks who want custom context attributes via middleware. User and Url are pretty ubiquitous, and the current middleware is clean and easy to use as a base for package users to add whatever additional attributes they want. This is what I did in a recent project and it has worked wonderfully.

Perhaps a suggestion should be added in the docs stating that package users who want custom attributes should subclass the middleware or create their own?

**Comment by wesleykendall** [comment]
FYI I updated pghistory's middleware to be a class instead of a function, allowing others to now inherit and override `get_context`. I added the example of IP address collection to the docs in https://github.com/Opus10/django-pghistory/pull/141

Will merge and get this out in the next released

**Pull request closed without merging**
