### PR TITLE
Optimise CTE query to use subquery instead of window function

### PR DESCRIPTION
**Pull request by lokhman**
On large datasets `LAG` window function will massively hit the performance.

To improve it, we should benefit from a simple sub-SELECT. The difference in speed is **enormous**!

Tested on the table with ~1 million rows:
- with `LAG`: ~ 40s
- with subquery: 448ms

### CODE REVIEW

**Comment by wesleykendall** [comment]
Wow! I'm in the midst of upgrading packages to ensure they're also tested against Postgres17. I put a reminder to apply this upgrade to pghistory tonight. If this passes, let me see if I can get both of these changes out together.

It's unclear to me at the moment why the tests fail. Let me know if you'd like me to try to investigate

**Comment by wesleykendall** [comment]
@lokhman I investigated things this morning. There seems to be a regression in the test suite specifically at [this line](https://github.com/Opus10/django-pghistory/blob/a035c964828bdc0c30041baf67d425493ff1301b/pghistory/tests/test_models.py#L743) and [this line](https://github.com/Opus10/django-pghistory/blob/a035c964828bdc0c30041baf67d425493ff1301b/pghistory/tests/test_models.py#L850).

The test suite is now reporting a `pgh_diff` of `'fk_field_id': [<int_val>, <int_val> ]`.

I'm having a difficult time understanding exactly what this test is testing, but I imagine there was a reason for putting it in place. It seems to try to deal with `null`s for the `pgh_obj` field.

I tried changing your `where` condition to a `is not distinct from` since I believe `partition` was treating nulls as equal, but the test reports the same result.

It's odd that the suite only reports a diff for these two rows in this test where the `pgh_obj_id` references a user. When I look at the test data being asserted, the last element does seem like it should have a `null` `pgh_diff` as asserted in the test since there is no change in `pgh_data` for the object that also references the same `pgh_obj_id`.

There is the chance that the test suite is inaccurate though.

are you able to easily run the suite locally? `pytest  pghistory/tests/test_models.py::test_events_references_no_obj_tracking_filters -vvv` should do the trick. You'll see a diff that looks like this at the end:

```
     {
  -         'pgh_context': None,
  -         'pgh_context_id': None,
  ?                     ---
  +         'pgh_context': None,
  -         'pgh_created_at': <ANY>,
  +         'pgh_context_id': None,
  +         'pgh_created_at': datetime.datetime(2024, 10, 29, 11, 31, 46, 863974, tzinfo=datetime.timezone.utc),
            'pgh_data': {
                'dt_field': '2020-06-22T00:00:00+00:00',
                'fk_field_id': 65,
                'id': 60,
                'int_field': 33,
            },
  -         'pgh_diff': None,
  ?                     ^^^^^
  +         'pgh_diff': {
  ?                     ^
  +             'fk_field_id': [
  +                 66,
  +                 65,
  +             ],
  +         },
  -         'pgh_id': <ANY>,
  ?                   ^^^^^
  +         'pgh_id': 149,
  ?                   ^^^
            'pgh_label': 'snapshot_update',
            'pgh_model': 'tests.SnapshotModelSnapshot',
            'pgh_obj_id': '60',
            'pgh_obj_model': 'tests.SnapshotModel',
  -         'pgh_slug': <ANY>,
  +         'pgh_slug': 'tests.SnapshotModelSnapshot:149',
        },
    ]
```

This diff is a bit misleading because pytest reports `<ANY>` as not being equal. However, the `pgh_diff` difference in this output is what is actually causing it to fail.

I will try to investigate more. It's been a while since I have used this specific functionality of pghistory. I know others have reported how bad the performance is though, so I'd love to get this in soon

**Comment by wesleykendall** [comment]
@lokhman I just verified that your code is producing the right results.

The former LAG query seems to be restricting the space when using `references`. It's difficult to explain. I checked out the two failing pieces of the test suite, which both show a `pgh_diff` of `null`. When examining the event history of those models, they should have a diff that shows their foreign key going from the previous user to the user being referenced, which is what your test returns.

The only outstanding question for me is if you should use a `is not distinct from` instead of a `=` so that nulls are treated as equal. I believe the answer is yes, but it doesn't produce any difference in the test suite. Let me know if you have any thoughts. Would like to get this in soon.

I'm happy to push a fix here to update the test suite

**Comment by lokhman** [comment]
@wesleykendall Uh, oh. I was looking in the wrong place. I can see now that it's a test `test_events_references_no_obj_tracking_filters` that is failing.

The issue doesn't look trivial, as you mentioned, so I'll need some time to investigate it too. I'm off the laptop today and will be able to check deeply tomorrow.

I'm not sure I understand why `IS NOT DISTINCT FROM` could make a difference here. I presume you mean using it in `WHERE _prev_event.pgh_obj_id = _event.pgh_obj_id` clause? Subselecting records where `NULL IS NULL` doesn't look possible. Or did I get you wrong?

I have a strong feeling that the problem is with the test, as the query should do its job correctly, but let's be 100% sure and get to the bottom of the failing test to prove it.

**Comment by wesleykendall** [comment]
@lokhman I should have been more clear with my follow up message. I believe your change here is actually correct and the test case was previously asserting invalid behavior. After looking into the underlying data of the test case, the new `pgh_diff` values that are surfaced seem to be correct.

The question I have is mostly if the `WHERE` should be `=` or `is not distinct from`. I haven't gotten a clear answer on if a postgres window partition will treat nulls as equal or not equal. I think it's actually the former.

My guess it that we probably want to use `=` here after thinking about it, meaning null!=null. This would ensure that cascade-deleted `pgh_obj` values in history rows would no longer be grouped together in a series. Unfortunately the test suite produces the same result if I use `=` or `is not distinct from` in the where clause, so it doesn't seem to exercise this case.

I'm feeling confident that we can go forward with your change after we update the test assertion, which I'm happy to do

**Comment by lokhman** [comment]
Understood. Thanks for looking into it. I'm happy that you were able to confirm that it works correct in this case. I agree with your thinking about `is not distinct from`.

**Comment by wesleykendall** [comment]
I'm going to merge this and update the tests in the release PR. Will let you know when released. Thanks again for this!

**Comment by wesleykendall** [comment]
Just deployed this in the 3.5.0 release. It should be on pypi within the next 15 minutes!

**Comment by 9128305** [comment]
@lokhman @wesleykendall I see opposite results for 3m+ rows: the lag function is much more performant than the subquery. What am I doing wrong?

**Pull request merged**
